//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apifortallientmaster.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Hirecraftv5Entities : DbContext
    {
        public Hirecraftv5Entities()
            : base("name=Hirecraftv5Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HC_RESUME_BANK> HC_RESUME_BANK { get; set; }
        public virtual DbSet<HC_USER_MAIN> HC_USER_MAIN { get; set; }
        public virtual DbSet<HC_USER> HC_USER { get; set; }
    
        public virtual int CandidateNumberGeneration(Nullable<long> mappingId)
        {
            var mappingIdParameter = mappingId.HasValue ?
                new ObjectParameter("MappingId", mappingId) :
                new ObjectParameter("MappingId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CandidateNumberGeneration", mappingIdParameter);
        }
    
        public virtual int usp_GetResumeDetailsForDuplicateCheck(string mobileNo, string emailID, ObjectParameter resID)
        {
            var mobileNoParameter = mobileNo != null ?
                new ObjectParameter("MobileNo", mobileNo) :
                new ObjectParameter("MobileNo", typeof(string));
    
            var emailIDParameter = emailID != null ?
                new ObjectParameter("EmailID", emailID) :
                new ObjectParameter("EmailID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_GetResumeDetailsForDuplicateCheck", mobileNoParameter, emailIDParameter, resID);
        }
    }
}
