//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apifortallientmaster.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class V5Entities1 : DbContext
    {
        public V5Entities1()
            : base("name=V5Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HC_CONFIG_TEMPLATE> HC_CONFIG_TEMPLATE { get; set; }
        public virtual DbSet<HC_USER_MAIN> HC_USER_MAIN { get; set; }
        public virtual DbSet<HCM_COUNTRY> HCM_COUNTRY { get; set; }
        public virtual DbSet<HCM_CURRENCY> HCM_CURRENCY { get; set; }
        public virtual DbSet<HCM_DESIGNATIONS> HCM_DESIGNATIONS { get; set; }
        public virtual DbSet<HCM_EDUCATION> HCM_EDUCATION { get; set; }
        public virtual DbSet<HCM_LOCATIONS> HCM_LOCATIONS { get; set; }
        public virtual DbSet<HCM_SKILLS> HCM_SKILLS { get; set; }
        public virtual DbSet<HCM_GENDER> HCM_GENDER { get; set; }
        public virtual DbSet<HCM_UNIVERSITY_GROUP> HCM_UNIVERSITY_GROUP { get; set; }
        public virtual DbSet<HCM_COMMON_MASTER> HCM_COMMON_MASTER { get; set; }
    }
}
