//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apifortallientmaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HC_CONFIG_TEMPLATE
    {
        public long RID { get; set; }
        public string Title { get; set; }
        public Nullable<long> PswTemplateID { get; set; }
        public Nullable<long> AccessRightTemID { get; set; }
        public Nullable<long> OrgTemplateID { get; set; }
        public Nullable<long> DesignTemplateID { get; set; }
        public long TID { get; set; }
        public Nullable<long> ResSearchLayoutID { get; set; }
    }
}
