//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apifortallientmaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HC_USER
    {
        public long RID { get; set; }
        public long UserID { get; set; }
        public short RoleID { get; set; }
        public bool Status { get; set; }
        public long TID { get; set; }
    }
}
