//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apifortallientmaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_COMMON_MASTER
    {
        public long RID { get; set; }
        public string Title { get; set; }
        public string RefID { get; set; }
        public short LanguageType { get; set; }
        public long EngKeyID { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public long TID { get; set; }
        public long RefType { get; set; }
        public short ConstValue { get; set; }
        public Nullable<short> NoOfEntries { get; set; }
        public Nullable<long> SequenceNo { get; set; }
        public string ControlNo { get; set; }
    }
}
